# Generated by Django 3.2.9 on 2021-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_phone', models.IntegerField(max_length=20)),
                ('cust_amount', models.IntegerField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
