# Generated by Django 3.2.9 on 2021-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cust_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cust_phone',
            field=models.IntegerField(),
        ),
    ]
