# Generated by Django 3.2.9 on 2021-12-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20211209_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='time',
        ),
    ]
