# Generated by Django 3.2.9 on 2021-12-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='time',
        ),
    ]
